### ISSUE TITLE
Duplicate createDatabase function in installation database model

### ISSUE THREAD

**Issue by phproberto** [Joomla3-Admin-template/joomla-cms#115]
Testing the Template9 branch I receive this error trying to install with a non-existent database.

Fatal error: Cannot redeclare InstallationModelDatabase::createDatabase() in /var/www/j30a2t9/installation/models/database.php on line 625

Seems to be declared in:
https://github.com/Joomla3-Admin-template/joomla-cms/blob/template9/installation/models/database.php#L151

And also in:
https://github.com/Joomla3-Admin-template/joomla-cms/blob/template9/installation/models/database.php#L625

I fixed the database creation in template8 branch and the function at line 625 was not there.

**Comment by realityking** [comment]
This should be fixed now. Thanks.
