### ISSUE TITLE
Fatal error when saving a module

### ISSUE THREAD

**Issue by kyleledbetter** [Joomla3-Admin-template/joomla-cms#16]
Getting these notices and fatal error when saving a module in template4 right now:

Notice: Trying to get property of non-object in /Users/kyle/Sites/joomla-cms/administrator/components/com_modules/models/module.php on line 806 

Notice: Trying to get property of non-object in /Users/kyle/Sites/joomla-cms/administrator/components/com_modules/models/module.php on line 809 Notice: Trying to get property of non-object in /Users/kyle/Sites/joomla-cms/administrator/components/com_modules/models/module.php on line 810 

Notice: Trying to get property of non-object in /Users/kyle/Sites/joomla-cms/administrator/components/com_modules/models/module.php on line 811 

Notice: Trying to get property of non-object in /Users/kyle/Sites/joomla-cms/administrator/components/com_modules/models/module.php on line 812 

Catchable fatal error: Argument 1 passed to ModulesControllerModule::postSaveHook() must be an instance of JModel, instance of ModulesModelModule given, called in /Users/kyle/Sites/joomla-cms/libraries/legacy/controller/form.php on line 792 and defined in /Users/kyle/Sites/joomla-cms/administrator/components/com_modules/controllers/module.php on line 135

Any ideas? :)

**Comment by realityking** [comment]
At least the last one is fixed in my joomla30 branch. Mark found a number of these by running the system tests, I don't have time right now but I'll rebase in a couple of days.
