### ISSUE TITLE
Login button bug (template 4)

### ISSUE THREAD

**Issue by Brightside56** [Joomla3-Admin-template/joomla-cms#18]
I have ugly login button (template4) in Mozilla 13.0.1 and Opera 12.

Screenshot: http://sc2.by/pics/images/mozilla.png

I found it:

Now  - http://jsfiddle.net/RVff4/
Propper usage - http://jsfiddle.net/zpQHu/

**Comment by mbabker** [comment]
Tested in Chrome 20 and Firefox 13, looks OK in both.  Fixed.
