### ISSUE TITLE
Error Messages in Installation not using Bootstrap markup

### ISSUE THREAD

**Issue by mbabker** [Joomla3-Admin-template/joomla-cms#22]
When getting an error message in the install app, the display is using the 2.5 style markup.

`<div id="system-message-container">
<dl id="system-message" role="alert"><dt class="warning">warning</dt><dd class="warning message"><ul><li>Field required: Database Name</li></ul></dd></dl></div>`

**Comment by vietvh** [comment]
What is the best way to commit code changes in this case?

**Comment by mbabker** [comment]
Right now, fork the template7 branch into your CMS repo, make changes, commit, and issue a pull request.  Right now, pull requests for the CMS are going to a 404 page, so just link to the commits here, and we can manually pull them in.

**Comment by vietvh** [comment]
Can you try with this diff first http://pastebin.com/xwMYih0z

**Comment by mbabker** [comment]
At a quick glance, it looks right code wise.  I can test it out later this afternoon when I'm at my laptop.

Also, pull requests are working again.

**Comment by mbabker** [comment]
Tested it, looks good.  Would you mind issuing a pull request for it?

Also, you'll need to send a pull request to the Platform since core.js is the Platform's JavaScript?

Lastly, @realityking would you mind ensuring that the right compression is being used?  The pastebin diff looks like it is using a different compression method.

**Comment by realityking** [comment]
We recently moved to closure on the platform since that saves a few bytes, I suggest we keep using it here. But in the end it doesn't matter too much.

**Comment by vietvh** [comment]
Ok I'll make pull requests for it.

As for the compression, I used UglifyJS but will try closure later.

**Comment by vietvh** [comment]
Here is the commit: 
https://github.com/vietvh/joomla-cms/commit/cf26484c828849f93280fd491512839f775939e9

Related Platform pull request:
https://github.com/joomla/joomla-platform/pull/1381

**Comment by realityking** [comment]
I closed the platform pull request for now, none of the bootstrap modifications have made it to the platform yet. We have to see how we handle that, but this would have to go in together with the modification to JDocumentHTMLRenderMessages.

**Comment by vietvh** [comment]
How about allowing template to override system message, just like we are doing for pagination, error etc?

**Comment by piotr-cz** [comment]
@vietvh 
That would be great, but there's a small catch: system messages HTML structure is also present in the JS code: core.js.
Template override would need to contain an override `Joomla.renderMessages` function with new structure.

I've done it, as current function is insufficient for me (discards old messages when adding new ones)

Another solution would be to use one template file that is server-side and client-side parseable ([Moustache.js](http://mustache.github.com/))
