### ISSUE TITLE
Joomla 3.0 alpha *  - actual demo

### ISSUE THREAD

**Issue by Brightside56** [Joomla3-Admin-template/joomla-cms#23]
It would be useful to have a working demo installation of actual alpha of joomla 3.0 on your host. Many people can't install every alpha build for testing. You would be able to receive a lot of feedback from it.

**Comment by mbabker** [comment]
The first Alpha release only contained the latest Platform code, so the JUX work isn't included.  Alpha 2, later this month, will include the work that's been going on here,

JoomlaShine is hosting a demo site at this time if you're interested.  Note that they are showing one of their templates at the front end versus the one distributed with core, but the backend has the default template.  That site is at http://joomla30.joomlashine.com/
