### ISSUE TITLE
Template 7 - Administrator login form issue FF14

### ISSUE THREAD

**Issue by Brightside56** [Joomla3-Admin-template/joomla-cms#29]
Look at this - http://sc2.by/pics/images/adminxnx.png

**Comment by kyleledbetter** [comment]
Seems like Firefox renders Chosen select boxes a few pixel too high. We'll need to either see if there's a fix from Chosen or make a Firefox-specific hack to fix

**Comment by Brightside56** [comment]
.input-prepend .add-on, .input-append .add-on
{
vertical-align: top;
}

or

.chzn-container
{
vertical-align: middle;
}

And I don't need pull request, because this parameters in template.less file, right?

**Comment by kyleledbetter** [comment]
Ah thanks! The vertical-align on the add-on fixed it :) I've pushed to template7. When it's a core less/css change you need to commit and submit a pull request for the less and compiled css
