### ISSUE TITLE
Trash default home hives mysql error

### ISSUE THREAD

**Issue by brianteeman** [Joomla3-Admin-template/joomla-cms#38]
Any attempt to trash the default menu item gives an error - correctly
Error
Cannot unpublish default home

But also a warning
Warning
exception 'UnexpectedValueException' with message 'MenusTableMenu::publish(Array, -2, 668) empty.' in /Applications/MAMP/htdocs/kyle/libraries/joomla/table/nested.php:886 Stack trace: #0 /Applications/MAMP/htdocs/kyle/libraries/legacy/model/admin.php(863): JTableNested->publish(Array, -2, '668') #1 /Applications/MAMP/htdocs/kyle/administrator/components/com_menus/models/item.php(1381): JModelAdmin->publish(Array, -2) #2 /Applications/MAMP/htdocs/kyle/libraries/legacy/controller/admin.php(191): MenusModelItem->publish(Array, -2) #3 /Applications/MAMP/htdocs/kyle/libraries/legacy/controller/legacy.php(710): JControllerAdmin->publish() #4 /Applications/MAMP/htdocs/kyle/administrator/components/com_menus/menus.php(18): JControllerLegacy->execute('trash') #5 /Applications/MAMP/htdocs/kyle/libraries/legacy/component/helper.php(361): require_once('/Applications/M...') #6 /Applications/MAMP/htdocs/kyle/libraries/legacy/component/helper.php(341): JComponentHelper::executeComponent('/Applications/M...') #7 /Applications/MAMP/htdocs/kyle/administrator/includes/application.php(151): JComponentHelper::renderComponent('com_menus') #8 /Applications/MAMP/htdocs/kyle/administrator/index.php(46): JAdministrator->dispatch() #9 {main}

**Comment by mbabker** [comment]
Can you check with the CMS master branch to see if you get the same message?  I'm fairly certain the uncaught exception hasn't anything to do with the work here.

FWIW, I think Rouven is working on a patch to convert the CMS code over to handle all these messages.

**Comment by infograf768** [comment]
The message displays in this template 7 branch and Rouven's php53 branch, not in master afaik
