### ISSUE TITLE
Two copies of strapped in template styles

### ISSUE THREAD

**Issue by elinw** [Joomla3-Admin-template/joomla-cms#47]
The template styles is showing two styles for each strapped even though the installation data has only one for each.

**Comment by mbabker** [comment]
I just updated the SQL Server DDL and installed on that and I'm getting the same problem.  My gut feeling is it has something to do with the naming.

**Comment by elinw** [comment]
I think so too. I also had a problem with copying it with the template copy
in the templatemanager and taht is usually related to naming also.

Elin

On Tue, Jul 31, 2012 at 8:14 PM, Michael Babker <
reply@reply.github.com

**Comment by kyleledbetter** [comment]
fixed in https://github.com/Joomla3-Admin-template/joomla-cms/commit/2aa7acf21d8ec839301dd0c77de13713c517d29b and https://github.com/Joomla3-Admin-template/joomla-cms/commit/94567275bddf8a9b270ea04faf66560e247c26d9
