### ISSUE TITLE
Installation Tab step 3

### ISSUE THREAD

**Issue by brianteeman** [Joomla3-Admin-template/joomla-cms#48]
If you are on the preinstall check page and then click on the tab for step 3 instead of clicking next then you get a progress bar that never progresses

**Comment by elinw** [comment]
Brian what browser/version are you on?

**Comment by brianteeman** [comment]
Google Chrome  20.0.1132.57 OS-x

**Comment by mbabker** [comment]
I think this was a known issue with directly clicking the tabs.  Can you check if this is an issue still with the installation rewrite that's been merged?

**Comment by brianteeman** [comment]
Yes it is still an issue

**Comment by kyleledbetter** [comment]
Lots of fixes going on today in the installation process, test again in a bit pls

**Comment by brianteeman** [comment]
Will have to be Sunday as I'm travelling back from Bulgaria tomorrow

Keep up the great work the changes are really awesome
