### ISSUE TITLE
View Site link

### ISSUE THREAD

**Issue by betweenbrain** [Joomla3-Admin-template/joomla-cms#49]
Just taking my first look at your fine work, which is fantastic, I noticed that the View Site link in admin is not present anymore. From experience and personal use, this is a very handy link to have. I know that many of my clients use it religiously and will miss it dearly. As it is right now, users may feel trapped in Admin when wanting to view their site and changes made to it.

**Comment by infograf768** [comment]
Unhappily, this View Site link is now in bottom bar and not separated from the User Status module, although we did separate these on purpose in 2.5.
Also, that bar is an obstacle when a combo is present at bottom of page. It also disapears when window width gets to short.

**Comment by betweenbrain** [comment]
I didn't even notice it there, nor did it occur to me to look at the bottom
of the page for it. I'm confident in saying that most users used to Joomla
2.5 will not look there, and many new ones may not see it either.

Since Logout has been added to the admin menu, in the upper right-and
corner, why not add View Site to that menu and eliminate the bottom bar by
moving the user counts and email icon to the top next to Settings?

Best,

Matt Thomas
Founder betweenbrain http://betweenbrain.com/™
Lead Developer Construct Template Development
Frameworkhttp://construct-framework.com/
Phone: 203.632.9322
Twitter: @betweenbrain
Github: https://github.com/betweenbrain

On Tue, Jul 31, 2012 at 7:54 AM, infograf768 <
reply@reply.github.com

**Comment by kyleledbetter** [comment]
Thanks for reporting Matt. Your comments are polite and well constructed. We'll get the View Site link worked into the top menu.

**Comment by betweenbrain** [comment]
Thanks!

Best,

Matt Thomas
Founder betweenbrain http://betweenbrain.com/™
Lead Developer Construct Template Development
Frameworkhttp://construct-framework.com/
Phone: 203.632.9322
Twitter: @betweenbrain
Github: https://github.com/betweenbrain

On Tue, Jul 31, 2012 at 11:43 AM, Kyle Ledbetter <
reply@reply.github.com

**Comment by kyleledbetter** [comment]
@betweenbrain pull template7 to test. Since we now have a Control Panel link I've change the sitename link to open the site url in a new window (and added an icon to indicate that)

**Comment by betweenbrain** [comment]
Thanks. Unfortunately, the installer hangs at the database installer step
due to https://github.com/Joomla3-Admin-template/joomla-cms/issues/102

Has this been merged into template9 so that I can test there?

Best,

Matt Thomas
Founder betweenbrain http://betweenbrain.com/™
Lead Developer Construct Template Development
Frameworkhttp://construct-framework.com/
Phone: 203.632.9322
Twitter: @betweenbrain
Github: https://github.com/betweenbrain

On Tue, Jul 31, 2012 at 12:53 PM, Kyle Ledbetter <
reply@reply.github.com

**Comment by mbabker** [comment]
template9 is where the fix is applied.

**Comment by betweenbrain** [comment]
Thanks! Will test template9 for this feature and respond there.

Best,

Matt Thomas
Founder betweenbrain http://betweenbrain.com/™
Lead Developer Construct Template Development
Frameworkhttp://construct-framework.com/
Phone: 203.632.9322
Twitter: @betweenbrain
Github: https://github.com/betweenbrain

**Comment by betweenbrain** [comment]
Maybe it would be better to respond here. I'm not seeing any change when looking for this fix in the template9 branch and Joomla Alpha2.

**Comment by infograf768** [comment]
@Matt the change is that the view site link is also now included in the site name at top left.

**Comment by betweenbrain** [comment]
Thanks JM! I would have never seen it up there if you didn't mention it. I
honestly expected to see it moved moved back to where it was, or maybe
under the Admin menu.

Best,

Matt Thomas
Founder betweenbrain http://betweenbrain.com/™
Lead Developer Construct Template Development
Frameworkhttp://construct-framework.com/
Phone: 203.632.9322
Twitter: @betweenbrain
Github: https://github.com/betweenbrain

**Comment by infograf768** [comment]
Me too
