### ISSUE TITLE
Batch process radio  in Article Manager

### ISSUE THREAD

**Issue by brianteeman** [Joomla3-Admin-template/joomla-cms#50]
The radio buttons for copy and move are misplaced in the article manager batch process dialog and flow directly following the select 

Shouldnt they be a sperate fieldset?

**Comment by infograf768** [comment]
These chnages to css would solve the issue (Tested with firebug)
.chzn-container {
    display: block;
    font-size: 13px;
    position: relative;
}

label {
    display: inline-block;
    margin-bottom: 5px;
}

**Comment by javigomez** [comment]
Confirmed, happens to me in Safari and Chrome for mac

**Comment by kyleledbetter** [comment]
fixed in https://github.com/Joomla3-Admin-template/joomla-cms/commit/ab18d21b910af013631588c3d3203534e49342a7
