### ISSUE TITLE
Routing / Breadcrumbs issue

### ISSUE THREAD

**Issue by elinw** [Joomla3-Admin-template/joomla-cms#55]
Not sure what is going on or why this branch should be causing a change in behavior, but compare the bread crumbs and routing for the Getting Started page in master and here and they are very very different and out of control (like when they were broken before the 1.6 release).

**Comment by kyleledbetter** [comment]
Weird, if you have any solutions please submit a pull request

**Comment by elinw** [comment]
I think this is a platform merge problem.

**Comment by realityking** [comment]
master and template branch are on the same platform version

**Comment by elinw** [comment]
I think it's actually okay so closing for now.
